tello/aruco_opencv_map:
  ros__parameters:
    header:
      frame_id: odom
    markers: [0, 1]
    
    marker_0:
      pose:
        position:
          x: 1.5
          y: 0.0
          z: 0.89
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    marker_1:
      pose:
        position:
          x: 1.5
          y: 0.52
          z: 0.89
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5