tello/aruco_opencv_map:
  ros__parameters:
    header:
      frame_id: odom
    markers: [1]

    # marker_0:
    #   pose:
    #     position:
    #       x: 1.0
    #       y: 0.0
    #       z: -0.4
    #     orientation:
    #       x: -0.270598050
    #       y: -0.653281482
    #       z: -0.270598050
    #       w:  0.653281482
    
    # marker_0:
    #   pose:
    #     position:
    #       x: 2.5
    #       y: -0.5
    #       z: 1.0
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: 0.0
    #       w: 1.0

    marker_1:
      pose:
        position:
          x: 1.5
          y: 0.0
          z: 0.7
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5