tello/control/pose_publisher:
  ros__parameters:

    thresh_x: 0.2
    thresh_y: 0.2
    thresh_z: 0.2
    thresh_total: 0.20

    header:
      frame_id: odom

    waypoint: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
               11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    waypoint_1:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 0°
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_2:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 90°
          x: 0.0
          y: 0.0
          z: 0.7071
          w: 0.7071

    waypoint_3:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 180°
          x: 0.0
          y: 0.0
          z: 1.0
          w: 0.0

    waypoint_4:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 270°
          x: 0.0
          y: 0.0
          z: 0.7071
          w: -0.7071

    waypoint_5:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 360° (=0°)
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_6:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 90°
          x: 0.0
          y: 0.0
          z: 0.7071
          w: 0.7071

    waypoint_7:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 180°
          x: 0.0
          y: 0.0
          z: 1.0
          w: 0.0

    waypoint_8:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 270°
          x: 0.0
          y: 0.0
          z: 0.7071
          w: -0.7071

    waypoint_9:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 360°
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_10:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 0° (start of next cycle)
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_11:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 90°
          x: 0.0
          y: 0.0
          z: 0.7071
          w: 0.7071

    waypoint_12:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 180°
          x: 0.0
          y: 0.0
          z: 1.0
          w: 0.0

    waypoint_13:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 270°
          x: 0.0
          y: 0.0
          z: 0.7071
          w: -0.7071

    waypoint_14:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 360° (=0°)
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_15:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 90°
          x: 0.0
          y: 0.0
          z: 0.7071
          w: 0.7071

    waypoint_16:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 180°
          x: 0.0
          y: 0.0
          z: 1.0
          w: 0.0

    waypoint_17:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 270°
          x: 0.0
          y: 0.0
          z: 0.7071
          w: -0.7071

    waypoint_18:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 360°
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_19:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 0°
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_20:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.0
        orientation:  # 90°
          x: 0.0
          y: 0.0
          z: 0.7071
          w: 0.7071
