tello/control/pose_publisher:
  ros__parameters:

    thresh_x: 0.2
    thresh_y: 0.2
    thresh_z: 0.2
    thresh_total: 0.20

    header:
      frame_id: odom

    waypoint: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
               11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
               21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
               31, 32]

    # -----------------------
    # Original WP1 + added checkpoints
    # -----------------------

    waypoint_1:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.4
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_2:    # NEW checkpoint
      pose:
        position:
          x: 0.5
          y: 0.0
          z: 1.4
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_3:    # NEW checkpoint
      pose:
        position:
          x: 1.0
          y: 0.0
          z: 1.4
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_4:    # Original waypoint_2 (1.5)
      pose:
        position:
          x: 1.5
          y: 0.0
          z: 1.4
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    # ------------------------------------------------------
    # ALL ORIGINAL WAYPOINTS START HERE, untouched
    # but shifted down by +2 index
    # ------------------------------------------------------

    waypoint_5:
      pose:
        position:
          x: 1.5
          y: 0.0
          z: 0.5
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_6:
      pose:
        position:
          x: 2.6
          y: 0.0
          z: 0.5
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_7:
      pose:
        position:
          x: 2.6
          y: 0.0
          z: 1.05
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_8:
      pose:
        position:
          x: 1.5
          y: 0.0
          z: 1.05
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_9:
      pose:
        position:
          x: 1.5
          y: 0.0
          z: 1.6
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_10:
      pose:
        position:
          x: 2.6
          y: 0.0
          z: 1.6
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_11:
      pose:
        position:
          x: 2.6
          y: 0.0
          z: 0.4
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_12:
      pose:
        position:
          x: 2.6
          y: 0.5
          z: 1.2
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_13:
      pose:
        position:
          x: 3.4
          y: 0.5
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_14:
      pose:
        position:
          x: 3.4
          y: 0.0
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_15:
      pose:
        position:
          x: 3.4
          y: -0.5
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_16:
      pose:
        position:
          x: 4.2
          y: -0.5
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_17:
      pose:
        position:
          x: 4.2
          y: 0.0
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_18:
      pose:
        position:
          x: 4.2
          y: 0.5
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_19:
      pose:
        position:
          x: 5.3
          y: 0.5
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_20:
      pose:
        position:
          x: 5.3
          y: 0.0
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_21:
      pose:
        position:
          x: 5.5
          y: 0.0
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_22:
      pose:
        position:
          x: 5.5
          y: 0.0
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_23:
      pose:
        position:
          x: 5.5
          y: 0.7
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: -0.7071067811865475
          w: 0.9238795325112867

    waypoint_24:
      pose:
        position:
          x: 6.2
          y: 0.7
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: -1.0
          w: 0.7071067811865476

    waypoint_25:
      pose:
        position:
          x: 6.9
          y: 0.7
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: -0.7071067811865476
          w: 0.38268343236508984

    waypoint_26:
      pose:
        position:
          x: 6.9
          y: 0.0
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_27:
      pose:
        position:
          x: 6.9
          y: -0.5
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: 0.7071067811865475
          w: -0.3826834323650897

    waypoint_28:
      pose:
        position:
          x: 6.2
          y: -0.5
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: 1.0
          w: -0.7071067811865475

    waypoint_29:
      pose:
        position:
          x: 5.5
          y: -0.5
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: 0.7071067811865477
          w: -0.9238795325112867

    waypoint_30:
      pose:
        position:
          x: 5.5
          y: 0.0
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_31:
      pose:
        position:
          x: 5.5
          y: 0.0
          z: 1.2
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_32:
      pose:
        position:
          x: 7.1
          y: 0.0
          z: 1.2
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0
