tello/control/pose_publisher:
  ros__parameters:

    thresh_x: 0.25
    thresh_y: 0.25
    thresh_z: 0.15


    thresh_total: 0.45




    header:
      frame_id: odom
    # waypoint: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
    waypoint: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

    waypoint_1:
      pose:
        position:
          x: 0.0
          y: 0.0
          z: 1.40
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_2:
      pose:
        position:
          x: 1.4
          y: 0.0
          z: 1.40
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_3:
      pose:
        position:
          x: 1.4
          y: 0.0
          z: 0.4
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_4:
      pose:
        position:
          x: 2.7
          y: -0.25
          z: 0.6
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_5:
      pose:
        position:
          x: 2.7
          y: 0.0
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_6:
      pose:
        position:
          x: 1.4
          y: 0.0
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_7:
      pose:
        position:
          x: 1.4
          y: 0.0
          z: 1.7
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_8:
      pose:
        position:
          x: 2.6
          y: -0.25
          z: 1.7
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    # # Zigzag
    # waypoint_9:
    #   pose:
    #     position:
    #       x: 2.6
    #       y: -0.50
    #       z: 1.2
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: 0.0
    #       w: 1.0

    # waypoint_10:
    #   pose:
    #     position:
    #       x: 2.6
    #       y: -0.5
    #       z: 1.0
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: 0.49999999999999994
    #       w: 0.9659258262890683

    # waypoint_11:
    #   pose:
    #     position:
    #       x: 3.4
    #       y: -0.5
    #       z: 1.0
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: 0.49999999999999994
    #       w: 0.9659258262890683

    # waypoint_12:
    #   pose:
    #     position:
    #       x: 3.4
    #       y: 0.0
    #       z: 1.0
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: 0.0
    #       w: 1.0

    # waypoint_13:
    #   pose:
    #     position:
    #       x: 3.4
    #       y: 0.5
    #       z: 1.0
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: -0.49999999999999994
    #       w: 0.9659258262890683

    # waypoint_14:
    #   pose:
    #     position:
    #       x: 4.2
    #       y: 0.5
    #       z: 1.0
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: -0.49999999999999994
    #       w: 0.9659258262890683

    # waypoint_15:
    #   pose:
    #     position:
    #       x: 4.2
    #       y: 0.0
    #       z: 1.0
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: 0.0
    #       w: 1.0

    # waypoint_16:
    #   pose:
    #     position:
    #       x: 4.2
    #       y: -0.5
    #       z: 1.0
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: 0.49999999999999994
    #       w: 0.9659258262890683

    # waypoint_17:
    #   pose:
    #     position:
    #       x: 5.3
    #       y: -0.5
    #       z: 1.0
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: 0.49999999999999994
    #       w: 0.9659258262890683

    # waypoint_18:
    #   pose:
    #     position:
    #       x: 5.3
    #       y: 0.0
    #       z: 1.0
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: 0.0
    #       w: 1.0

    # waypoint_19:
    #   pose:
    #     position:
    #       x: 5.5
    #       y: 0.0
    #       z: 1.0
    #     orientation:
    #       x: 0.0
    #       y: 0.0
    #       z: 0.0
    #       w: 1.0

    # Zigzag
    waypoint_9:
      pose:
        position:
          x: 2.6
          y: -0.50
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_10:
      pose:
        position:
          x: 2.6
          y: -0.5
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_11:
      pose:
        position:
          x: 3.55
          y: -0.5
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_12:
      pose:
        position:
          x: 3.55
          y: 0.0
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_13:
      pose:
        position:
          x: 3.55
          y: 0.5
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_14:
      pose:
        position:
          x: 4.3
          y: 0.5
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_15:
      pose:
        position:
          x: 4.2
          y: 0.0
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_16:
      pose:
        position:
          x: 4.2
          y: -0.5
          z: 1.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_17:
      pose:
        position:
          x: 5.3
          y: -0.5
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_18:
      pose:
        position:
          x: 5.3
          y: 0.0
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_19:
      pose:
        position:
          x: 5.3
          y: 0.0
          z: 0.8
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    # Circle pattern
    waypoint_19:
      pose:
        position:
          x: 5.3
          y: 0.00
          z: 0.80
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_20:
      pose:
        position:
          x: 5.70      # angle 180°
          y: 0.00
          z: 0.80
        orientation:   # yaw = 0° (facing +x toward plant)
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    waypoint_21:
      pose:
        position:
          x: 5.9      # angle 225°
          y: -0.65
          z: 0.80
        orientation:   # yaw ≈ +45°
          x: 0.0
          y: 0.0
          z: 0.3826834324
          w: 0.9238795325

    waypoint_22:
      pose:
        position:
          x: 6.55      # angle 270°
          y: -0.65
          z: 0.80
        orientation:   # yaw ≈ +90°
          x: 0.0
          y: 0.0
          z: 0.7071067812
          w: 0.7071067812

    waypoint_23:
      pose:
        position:
          x: 1.71      # angle 315°
          y: -0.46
          z: 0.80
        orientation:   # yaw ≈ +135°
          x: 0.0
          y: 0.0
          z: 0.9238795325
          w: 0.3826834324

    waypoint_24:
      pose:
        position:
          x: 7.2      # angle   0°
          y: 0.00
          z: 0.80
        orientation:   # yaw = 180° (facing back toward plant)
          x: 0.0
          y: 0.0
          z: 1.0
          w: 0.0

    waypoint_25:
      pose:
        position:
          x: 7.01      # angle  45°
          y: 0.46
          z: 0.80
        orientation:   # yaw ≈ -135°
          x: 0.0
          y: 0.0
          z: -0.9238795325
          w: 0.3826834324

    waypoint_26:
      pose:
        position:
          x: 6.55      # angle  90°
          y: 0.65
          z: 0.80
        orientation:   # yaw ≈ -90°
          x: 0.0
          y: 0.0
          z: -0.7071067812
          w: 0.7071067812

    waypoint_27:
      pose:
        position:
          x: 6.09      # angle 135°
          y: 0.46
          z: 0.80
        orientation:   # yaw ≈ -45°
          x: 0.0
          y: 0.0
          z: -0.3826834324
          w: 0.9238795325

    # Optional, to explicitly close the loop back to the front:
    waypoint_28:
      pose:
        position:
          x: 5.9
          y: 0.00
          z: 0.80
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

